app/controllers/individual/IndWhereDoYouLiveController.scala, app/forms/IndWhereDoYouLiveFormProvider.scala, app/navigation/Navigator.scala, app/pages/IndWhereDoYouLivePage.scala, app/views/individual/IndWhereDoYouLiveView.scala.html, conf/app.routes, conf/messages.en, test-utils/generators/ModelGenerators.scala, test/controllers/individual/IndSelectAddressControllerSpec.scala, test/controllers/individual/IndWhereDoYouControllerSpec.scala, test/forms/IndWhereDoYouLiveFormProviderSpec.scala, test/navigation/NavigatorSpec.scala
Please Note: The place-holder`IndWhereDoYouLive` page was created to enable testing of this ticket even though the final implementation has been deferred due to redesign [DAC6-2727](https://jira.tools.tax.service.gov.uk/browse/DAC6-2727).
When the redesign is complete, then the `IndWhereDoYouLive` page will be updated.
=> DAC6-2917: Navigation for individual without Id

app/controllers/ControllerHelper.scala, app/controllers/RegistrationConfirmationController.scala, app/views/RegistrationConfirmationView.scala.html, app/views/components/Heading.scala.html, conf/app.routes, conf/messages.en, test/controllers/CheckYourAnswersControllerSpec.scala, test/controllers/ControllerHelperSpec.scala, test/controllers/RegistrationConfirmationControllerSpec.scala, test/controllers/individual/IndIdentityConfirmedControllerSpec.scala
=> DAC6-3013: confirmation page added

app/services/BusinessMatchingWithoutIdService.scala, test/services/BusinessMatchingWithoutIdServiceSpec.scala
Further work required to fix up all journeys. I don't think the current approach leads itself to easy unit testing so some further refactoring will be required.
=> Fix for some user registration journeys

app/models/subscription/request/ContactType.scala, test/services/SubscriptionServiceSpec.scala
The wrong page details were being used for the individual without id journey
* IndWhatIsYourNamePage = Individual without ID
* IndContactNamePage = Individual with ID
* WhatIsYourNamePage = Sole trader
=> Fix for contact name used for subscription

.scalafmt.conf, app/controllers/CheckYourAnswersController.scala, app/controllers/individual/IndIsThisYourAddressController.scala, app/models/subscription/request/ContactType.scala, app/models/subscription/request/CreateSubscriptionRequest.scala, app/services/BusinessMatchingWithoutIdService.scala, app/services/SubscriptionService.scala, test-utils/generators/Generators.scala, test/controllers/CheckYourAnswersControllerSpec.scala, test/models/subscription/CreateSubscriptionRequestSpec.scala, test/models/subscription/request/ContactTypeSpec.scala, test/services/BusinessMatchingWithoutIdServiceSpec.scala, test/services/SubscriptionServiceSpec.scala
Fixed issues with registration journeys. Should now allow all of the different registration types to complete registration
=> DAC6-3104: Fixed up registration journeys

app/controllers/DetailsUpdatedController.scala, app/views/DetailsUpdatedView.scala.html, app/views/components/Link.scala.html, conf/app.routes, conf/messages.en
=> DAC6-3006: details updated confirmation page

app/navigation/Navigator.scala, app/utils/ChangeOrganisationContactDetailsHelper.scala, app/viewmodels/changeContactDetails/OrganisationContactEmailSummary.scala, conf/messages.en, test/navigation/NavigatorSpec.scala
This PR fixes the:
- Visually-hidden text for the org change contact details page
- The navigation for the org change contact details
=> DAC6-3001: Fix content changes and navigation

app/controllers/DetailsUpdatedController.scala, app/controllers/actions/StandardActionSets.scala, app/controllers/actions/SubscriptionIdRetrievalAction.scala, app/models/subscription/response/DisplaySubscriptionResponse.scala, app/models/subscription/response/RegistrationType.scala, test/controllers/DetailsUpdatedControllerSpec.scala, test/controllers/actions/FakeSubscriptionIdRetrievalAction.scala, test/controllers/changeContactDetails/ChangeIndividualContactDetailsControllerSpec.scala, test/controllers/changeContactDetails/ChangeOrganisationContactDetailsControllerSpec.scala, test/controllers/changeContactDetails/IndividualEmailControllerSpec.scala, test/controllers/changeContactDetails/IndividualHavePhoneControllerSpec.scala, test/controllers/changeContactDetails/IndividualPhoneControllerSpec.scala, test/controllers/changeContactDetails/OrganisationContactEmailControllerSpec.scala, test/controllers/changeContactDetails/OrganisationContactHavePhoneControllerSpec.scala, test/controllers/changeContactDetails/OrganisationContactNameControllerSpec.scala, test/controllers/changeContactDetails/OrganisationContactPhoneControllerSpec.scala, test/controllers/changeContactDetails/OrganisationHaveSecondContactControllerSpec.scala, test/controllers/changeContactDetails/OrganisationSecondContactEmailControllerSpec.scala, test/controllers/changeContactDetails/OrganisationSecondContactHavePhoneControllerSpec.scala, test/controllers/changeContactDetails/OrganisationSecondContactNameControllerSpec.scala, test/controllers/changeContactDetails/OrganisationSecondContactPhoneControllerSpec.scala
Also added subscription details (Is organisation or individual) dependency instead
=> DAC6-3214 | Removed affinityGroup dependency

app/utils/RegexConstants.scala, test-utils/generators/Generators.scala, test/utils/RegexConstantsSpec.scala
Brings registration validation in line with the enrolment validation.
Registration is slightly stricter, but anything passing the registration validation will pass the enrolment validation.
Also - removed unused regular expressions from constants file.
=> DAC6-3242: Updated postcode regex

app/config/FrontendAppConfig.scala, app/views/RegistrationConfirmationView.scala.html, conf/application.conf
Add FI link now takes the user to the add FI route
=> DAC6-3236: Updated confirmation page

app/pages/ReporterTypePage.scala, test/pages/ReporterTypePageSpec.scala
- cleanup added for sole trader
- current test answers in this spec triggers other page cleanups and therefore affects what is being tested here so i've attempted to minimise it
=> DAC6-3296: cleanup for sole trader and spec redux

app/views/changeContactDetails/ChangeOrganisationContactDetailsView.scala.html
=> DAC6-3495: make subheading an h2

app/navigation/Navigator.scala, test/navigation/NavigatorSpec.scala
Refactored navigation logic to improve clarity and ensure consistent redirection to CheckYourAnswersPage based on user input. Introduced `yesNoNavigate` helper function to simplify conditional navigation handling.
=> DAC6-3480: Streamline navigation logic

app/config/FrontendAppConfig.scala, app/controllers/organisation/WhatIsYourUTRController.scala, app/forms/mappings/Formatters.scala, app/utils/RegexConstants.scala, app/views/organisation/WhatIsYourUTRView.scala.html, conf/application.conf, conf/messages.en, test/controllers/organisation/WhatIsYourUTRControllerSpec.scala
Add new content for UTR types. Update regex to allow for K and 10|13 digits. Add new spec for partnership type.
=> DAC6-3501 - Update /utr page content 

test-utils/generators/Generators.scala, test/controllers/CheckYourAnswersControllerSpec.scala, test/controllers/IsThisYourBusinessControllerSpec.scala, test/controllers/individual/IndIdentityConfirmedControllerSpec.scala, test/controllers/organisation/WhatIsYourUTRControllerSpec.scala, test/forms/WhatIsYourUTRFormProviderSpec.scala, test/forms/behaviours/StringFieldBehaviours.scala
- form providerSpec was expecting an error for a UTR length 13, this needed to be updated
- also resolved some sbt warnings
=> DAC6-3501 pt2: update spec to allow utr lengths of 10 and 13

app/models/IdentifierType.scala, app/models/subscription/request/UpdateSubscriptionRequest.scala
Replaced the IdentifierType from FATCAID to ZCRF in UpdateSubscriptionRequest. Added ZCRF as a valid identifier type in the IdentifierType model. This ensures compatibility with updated subscription requirements.
=> DAC6-3597: Update identifier to ZCRF

app/assets/javascripts/app.js, app/utils/CountryListFactory.scala, test/utils/CountryListFactorySpec.scala
=> DAC6-3579 | Amended JS and countrySelectList methods. 

app/viewmodels/changeContactDetails/OrganisationContactNameSummary.scala, app/viewmodels/changeContactDetails/OrganisationSecondContactNameSummary.scala, app/viewmodels/checkAnswers/BusinessNameWithoutIDSummary.scala, app/viewmodels/checkAnswers/BusinessTradingNameWithoutIDSummary.scala, app/viewmodels/checkAnswers/ContactNameSummary.scala, app/viewmodels/checkAnswers/IndContactNameSummary.scala, app/viewmodels/checkAnswers/SecondContactNameSummary.scala, app/viewmodels/checkAnswers/WhatIsYourNameSummary.scala
Replaced htmlformat.escape into Text component as advised in doc
=> updated with text component for dynamic contents

app/controllers/changeContactDetails/OrganisationContactEmailController.scala, app/forms/changeContactDetails/OrganisationContactEmailFormProvider.scala, test/controllers/changeContactDetails/OrganisationContactEmailControllerSpec.scala, test/forms/changeContactDetails/OrganisationContactEmailFormProviderSpec.scala
Updated correct name in form provider
Renamed form provider to match other files
=> updated correct constant names and renamed form provider

app/viewmodels/checkAnswers/IndContactNameSummary.scala
Reverted text component changes to have existing behaviour
=> reverted text component changes

app/pages/BusinessNamePage.scala, app/pages/WhatIsYourNamePage.scala, app/pages/WhatIsYourUTRPage.scala, test/controllers/IsThisYourBusinessControllerSpec.scala, test/pages/BusinessNamePageTest.scala, test/pages/WhatIsYourNamePageTest.scala, test/pages/WhatIsYourUTRPageTest.scala
Fixed mentioned bug by removing registrationInfo & IsThisBusiness objects 
Added test
=> Removed registrationInfo & IsThisYourBusiness Page as cleanup

app/views/UnauthorisedStandardUserView.scala.html, conf/messages.en, test/controllers/UnauthorisedStandardUserControllerSpec.scala, test/views/UnauthorisedStandardUserViewSpec.scala
=> DAC6-3722 | update content on Unauthorised page

app/config/FrontendAppConfig.scala, app/controllers/organisation/PreRegisteredController.scala, app/views/organisation/PreRegisteredView.scala.html, conf/app.routes, conf/application.conf, conf/messages.en, test/controllers/organisation/PreRegisteredControllerSpec.scala, test/views/PreRegisteredViewSpec.scala
=> DAC6-3782 | Content updated, link to manage-services-frontend added
