- README.md
- project/plugins.sbt
- test/resources/application.conf
Updated sbt-auto-build to latest to prevent the copyright dates being refreshed each year, plus addressed some small PR builder bot suggestions.
> Updated sbt-auto-build

- app/pages/IndNonUKAddressWithoutIdPage.scala
- app/pages/IndUKAddressWithoutIdPage.scala
- app/pages/IndWhereDoYouLivePage.scala
- test/pages/IndUKAddressWithoutIdPageSpec.scala
- test/pages/IndWhereDoYouLivePageSpec.scala
This PR fixes the QA issue raised where if a user goes to the change address page the previously entered values are cleared from the text boxes because `IndNonUKAddressWithoutIdPage` is cleared.
> DAC6-3018: Fix change address

- app/controllers/individual/IndCouldNotConfirmIdentityController.scala
- app/pages/PageLists.scala
We do not need to clear the user info out when they land on this page. Removed the functionality that does that.
> DAC6-3156: Updated individual "could not confirm identity" page logic

- app/controllers/ControllerHelper.scala
- app/utils/CheckYourAnswersValidator.scala
- test/controllers/ControllerHelperSpec.scala
Update `checkIndividualAddressMissingAnswers` to include validation for `IndUKAddressWithoutIdPage` in addition to `IndWhatIsYourPostcodePage`. This ensures that the validation process considers both pages when checking individual address details.
> DAC6-3331: Modify address validation logic for individual user flow

- app/controllers/organisation/IsThisYourBusinessController.scala
- test/controllers/IsThisYourBusinessControllerSpec.scala
Update redirection logic to handle missing CT UTR for sole traders. Added a new condition to redirect to SoleTraderNotIdentifiedController when appropriate. Updated tests to cover this new redirection path.
> DAC6-3367: Fix sole trader redirect

- project/AppDependencies.scala
- project/plugins.sbt
Upgraded multiple dependencies in AppDependencies.scala for improved compatibility and stability, including bootstrap from 9.1.0 to 9.5.0 and play-frontend-hmrc-play from 10.5.0 to 10.13.0. Also updated the sbt-plugin in plugins.sbt from 3.0.4 to 3.0.5.
> DAC6-3330: Update dependencies

- app/models/enrolment/SubscriptionInfo.scala
- test/models/enrolment/SubscriptionInfoSpec.scala
Refactored SubscriptionInfo to include individual registration address information. Added tests to verify the inclusion of postcode and abroad flag for individual (Ind) registration info.
> DAC6-3338: Change Verifiers for individuals

- app/connectors/AddressLookupConnector.scala
- app/models/Regime.scala
- app/models/register/request/RegisterWithID.scala
- app/models/register/request/RegisterWithoutID.scala
- test/connectors/RegistrationConnectorSpec.scala
- test/helpers/JsonFixtures.scala
Updated regime constant from CRSFATCA to CRFA across the codebase. This change ensures consistency with the new regime naming conventions.
> DAC6-3457: Rename regime constant

- app/controllers/RegistrationConfirmationController.scala
Replace `identifiedUserWithData()` with `identifiedWithoutEnrolmentCheck()` in `onPageLoad`. This change ensures the enrolment check is bypassed while maintaining the rest of the user identification flow.
> DAC6-3536: Update action set

- app/controllers/RegistrationConfirmationController.scala
- app/controllers/actions/IdentifierAction.scala
- app/controllers/actions/StandardActionSets.scala
- test/controllers/actions/FakeIdentifierAction.scala
Introduce a `redirect` parameter in `IdentifierAction` and related classes to control redirection behavior. Update `StandardActionSets` with a new method for handling actions without enrolment checks and disabling redirects. Adjust corresponding logic in `RegistrationConfirmationController` to use the new functionality.
> DAC6-3536: Add redirect control to IdentifierAction

- app/controllers/ControllerHelper.scala
- app/controllers/RegistrationConfirmationController.scala
- app/views/RegistrationConfirmationView.scala.html
- test/controllers/RegistrationConfirmationControllerSpec.scala
Reordered `createEnrolment` invocation to ensure user answers are updated after enrollment is created. Replaced `userId` with `fatcaId` in RegistrationConfirmationView and updated view rendering logic accordingly. Enhanced tests to validate scenarios with missing or invalid SubscriptionID.
> DAC6-3539: Refactor subscription handling

- app/assets/javascripts/app.js
Add logic to propagate the autocomplete attribute from the original select element to the combo element if it exists. Ensures better compatibility and adherence to form input behavior expectations.
> DAC6-3580: Set autocomplete attribute

- README.md
- project/AppDependencies.scala
- project/plugins.sbt
org.playframework:sbt-plugin 3.0.5  -> 3.0.6
uk.gov.hmrc: sbt-distributables 2.5.0 -> 2.6.0
uk.gov.hmrc.mongo: hmrc-mongo-play-30 2.2.0 -> 2.5.0
uk.gov.hmrc: bootstrap-frontend-play-30 9.5.0 -> 9.11.0
uk.gov.hmrc: crypto-json-play-30 8.1.0 -> 8.2.0
uk.gov.hmrc: play-frontend-hmrc-play-30 10.13.0 -> 11.12.0
uk.gov.hmrc.mongo: hmrc-mongo-test-play-30 2.2.0 -> 2.5.0
uk.gov.hmrc: bootstrap-test-play-30 9.5.0. -> 9.11.0
> Dac6-3570 : Updated dependencies 

- app/assets/javascripts/app.js
- app/utils/CountryListFactory.scala
- test/utils/CountryListFactorySpec.scala
Deleted obsolete code handling form submission to ensure cleaner and more maintainable scripts. The logic was no longer necessary and could cause unexpected behavior under certain conditions.
> DAC6-3581: Remove redundant form submission logic

- app/assets/javascripts/app.js
Wrap the `enhanceSelectElement` call in a `setTimeout` to ensure delayed execution. This change prevents initialization issues and ensures proper rendering of the accessible autocomplete component.
> DAC6-3581: Delay autocomplete init

- test/pages/DoYouHaveUniqueTaxPayerReferencePageSpec.scala
- test/pages/IndDoYouHaveNINumberPageSpec.scala
- test/pages/IsThisYourBusinessPageSpec.scala
- test/pages/RegisteredAddressInUKPageSpec.scala
- test/pages/ReporterTypePageSpec.scala
add a generator condition to disallow null/empty generated data to avoid occasional None.get's
> TECHDEBT: address flaky spec generators

- test-utils/generators/Generators.scala
- test-utils/generators/ModelGenerators.scala
Replaced arbitrary string generators with a defined `nonEmptyString` generator to ensure non-empty values in tests. This change improves reliability and clarity for test data generation across multiple models.
> DAC6-3672: Refactor string generators

- app/connectors/EnrolmentStoreProxyConnector.scala
- app/connectors/TaxEnrolmentsConnector.scala
- app/controllers/CheckYourAnswersController.scala
- app/controllers/actions/IdentifierAction.scala
- app/controllers/actions/StandardActionSets.scala
- app/controllers/individual/IndividualAlreadyRegisteredController.scala
- app/controllers/organisation/PreRegisteredController.scala
- app/models/enrolment/EnrolmentResponse.scala
- app/models/requests/IdentifierRequest.scala
- project/AppDependencies.scala
- test/connectors/EnrolmentStoreProxyConnectorSpec.scala
- test/controllers/RegistrationConfirmationControllerSpec.scala
- test/controllers/actions/AuthActionSpec.scala
- test/controllers/actions/FakeIdentifierAction.scala
Introduce the `EnrolmentResponse` model to handle enrolment-related API responses. Refactor the logic in `EnrolmentStoreProxyConnector` to enhance error handling and incorporate checks for existing enrolments using the new model.
> DAC6-3546: Add EnrolmentResponse model

- app/controllers/organisation/IsThisYourBusinessController.scala
- test/controllers/IsThisYourBusinessControllerSpec.scala
Removed unused `getSubscription` calls from tests and adjusted controller logic to streamline subscription handling. This change simplifies the codebase and ensures more efficient execution by eliminating redundant service calls.
> DAC6-3546: Update subscription handling

- app/connectors/EnrolmentStoreProxyConnector.scala
- app/connectors/TaxEnrolmentsConnector.scala
- app/controllers/actions/IdentifierAction.scala
- app/controllers/actions/StandardActionSets.scala
- app/controllers/individual/IndContactEmailController.scala
- app/controllers/individual/IndIdentityConfirmedController.scala
- app/controllers/individual/IndividualAlreadyRegisteredController.scala
- app/controllers/organisation/PreRegisteredController.scala
- app/models/requests/IdentifierRequest.scala
- test-utils/generators/UserAnswersGenerator.scala
- test/connectors/EnrolmentStoreProxyConnectorSpec.scala
- test/controllers/RegistrationConfirmationControllerSpec.scala
- test/controllers/actions/AuthActionSpec.scala
- test/controllers/actions/FakeIdentifierAction.scala
- test/controllers/individual/IndContactEmailControllerSpec.scala
- test/controllers/individual/IndIdentityConfirmedControllerSpec.scala
Removed logic and dependencies related to group enrolment checks, including unused connector methods, parameters, and tests. This simplifies the codebase and reduces unnecessary complexity.
> DAC6-3546: Remove group enrolment checks
